### ISSUE TITLE
Auto update flake.lock

### ISSUE THREAD

**Issue by shivaraj-bh** [flake-parts/community.flake.parts#9]
How about we use https://github.com/DeterminateSystems/update-flake-lock with [mergify](https://github.com/marketplace/mergify) to automate this?

**Comment by srid** [comment]
Feel free to set one up. 

I note that the main flake-parts repo is updated in HCI, which could be another option as well (but that requires setting HCI first).

https://github.com/hercules-ci/flake-parts/commit/a92a54c1b6374cfbd3672a37e394637eb4bbd379

**Comment by roberth** [comment]
I've set up an agent and opened #10 for the updater config. Is the goal for this to work the same as flake.parts?

**Comment by srid** [comment]
Great. At some point we can even migrate the gh-pages workflow to HCI and retire Github Actions entirely.
